// <auto-generated />
using System;
using ContentDB.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContentDB.Infrastructure.Data.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925144400_AddMultiplayer")]
    partial class AddMultiplayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentDB.Core.Domain.APIToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientId")
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PackageId");

                    b.ToTable("api_token", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CauserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CauserId");

                    b.HasIndex("PackageId");

                    b.ToTable("audit_log_entry", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Pinned")
                        .HasColumnType("boolean");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId", "Name")
                        .IsUnique();

                    b.ToTable("collection", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.CollectionPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("PackageId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("collection_package", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.ContentWarning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("content_warning", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Dependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DependerId")
                        .HasColumnType("integer");

                    b.Property<int?>("MetaPackageId")
                        .HasColumnType("integer");

                    b.Property<bool>("Optional")
                        .HasColumnType("boolean");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetaPackageId");

                    b.HasIndex("PackageId");

                    b.HasIndex("DependerId", "PackageId", "MetaPackageId")
                        .IsUnique();

                    b.ToTable("dependency", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.DevicePairing", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("device_pairing", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.ForumTopic", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.Property<bool>("Wip")
                        .HasColumnType("boolean");

                    b.HasKey("TopicId");

                    b.HasIndex("AuthorId");

                    b.ToTable("forum_topic", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.FriendLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddresseeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("friend_link", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.GameServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Listed")
                        .HasColumnType("boolean");

                    b.Property<string>("Motd")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersMax")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersOnline")
                        .HasColumnType("integer");

                    b.Property<string>("ReportTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReportTokenPrefix")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset?>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("game_server", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("language", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFoss")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("license", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsFoss = false,
                            Name = "Other"
                        },
                        new
                        {
                            Id = 2,
                            IsFoss = true,
                            Name = "MIT",
                            Url = "https://opensource.org/licenses/MIT"
                        },
                        new
                        {
                            Id = 3,
                            IsFoss = true,
                            Name = "Apache-2.0",
                            Url = "https://www.apache.org/licenses/LICENSE-2.0"
                        },
                        new
                        {
                            Id = 4,
                            IsFoss = true,
                            Name = "GPL-2.0",
                            Url = "https://www.gnu.org/licenses/old-licenses/gpl-2.0.html"
                        },
                        new
                        {
                            Id = 5,
                            IsFoss = true,
                            Name = "GPL-3.0",
                            Url = "https://www.gnu.org/licenses/gpl-3.0.html"
                        },
                        new
                        {
                            Id = 6,
                            IsFoss = true,
                            Name = "LGPL-2.1",
                            Url = "https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html"
                        },
                        new
                        {
                            Id = 7,
                            IsFoss = true,
                            Name = "LGPL-3.0",
                            Url = "https://www.gnu.org/licenses/lgpl-3.0.html"
                        },
                        new
                        {
                            Id = 8,
                            IsFoss = true,
                            Name = "AGPL-3.0",
                            Url = "https://www.gnu.org/licenses/agpl-3.0.html"
                        },
                        new
                        {
                            Id = 9,
                            IsFoss = true,
                            Name = "BSD-2-Clause",
                            Url = "https://opensource.org/licenses/BSD-2-Clause"
                        },
                        new
                        {
                            Id = 10,
                            IsFoss = true,
                            Name = "BSD-3-Clause",
                            Url = "https://opensource.org/licenses/BSD-3-Clause"
                        },
                        new
                        {
                            Id = 11,
                            IsFoss = true,
                            Name = "CC0-1.0",
                            Url = "https://creativecommons.org/publicdomain/zero/1.0/"
                        },
                        new
                        {
                            Id = 12,
                            IsFoss = true,
                            Name = "CC-BY-3.0",
                            Url = "https://creativecommons.org/licenses/by/3.0/"
                        },
                        new
                        {
                            Id = 13,
                            IsFoss = true,
                            Name = "CC-BY-4.0",
                            Url = "https://creativecommons.org/licenses/by/4.0/"
                        },
                        new
                        {
                            Id = 14,
                            IsFoss = true,
                            Name = "CC-BY-SA-3.0",
                            Url = "https://creativecommons.org/licenses/by-sa/3.0/"
                        },
                        new
                        {
                            Id = 15,
                            IsFoss = true,
                            Name = "CC-BY-SA-4.0",
                            Url = "https://creativecommons.org/licenses/by-sa/4.0/"
                        });
                });

            modelBuilder.Entity("ContentDB.Core.Domain.LuantiRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("luanti_release", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.MetaPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("meta_package", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CauserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Emailed")
                        .HasColumnType("boolean");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CauserId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.OAuthClient", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsClientSide")
                        .HasColumnType("boolean");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("RedirectUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("oauth_client", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiDisclosure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int?>("CoverImageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<string>("DevState")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DonateUrl")
                        .HasColumnType("text");

                    b.Property<int>("Downloads")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableGameSupportDetection")
                        .HasColumnType("boolean");

                    b.Property<int?>("Forums")
                        .HasColumnType("integer");

                    b.Property<string>("HttpApiJustification")
                        .HasColumnType("text");

                    b.Property<string>("InsecureEnvJustification")
                        .HasColumnType("text");

                    b.Property<string>("IssueTracker")
                        .HasColumnType("text");

                    b.Property<int>("LicenseId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaLicenseId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Repo")
                        .HasColumnType("text");

                    b.Property<int?>("ReviewThreadId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreDownloads")
                        .HasColumnType("double precision");

                    b.Property<bool>("SensitivePackage")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("SupportsAllGames")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranslationUrl")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoverImageId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("MediaLicenseId");

                    b.HasIndex("ReviewThreadId");

                    b.HasIndex("AuthorId", "Name")
                        .IsUnique();

                    b.ToTable("package", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("package_alias", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageDailyStats", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DownloadsV510")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformMinetest")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformOther")
                        .HasColumnType("integer");

                    b.Property<int>("ReasonDependency")
                        .HasColumnType("integer");

                    b.Property<int>("ReasonNew")
                        .HasColumnType("integer");

                    b.Property<int>("ReasonUpdate")
                        .HasColumnType("integer");

                    b.Property<int>("ViewsLuanti")
                        .HasColumnType("integer");

                    b.HasKey("PackageId", "Date");

                    b.ToTable("package_daily_stats", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageGameSupport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<bool>("Supports")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("GameId", "PackageId")
                        .IsUnique();

                    b.ToTable("package_game_support", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommitHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Downloads")
                        .HasColumnType("integer");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxRelId")
                        .HasColumnType("integer");

                    b.Property<int?>("MinRelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseNotes")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaskId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool?>("UsesHttpApi")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UsesInsecureEnv")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MaxRelId");

                    b.HasIndex("MinRelId");

                    b.HasIndex("PackageId");

                    b.ToTable("package_release", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LanguageId")
                        .HasColumnType("text");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<int?>("ThreadId")
                        .HasColumnType("integer");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ThreadId");

                    b.ToTable("package_review", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageReviewVote", b =>
                {
                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("boolean");

                    b.HasKey("ReviewId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("package_review_vote", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageScreenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("package_screenshot", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageTranslation", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageId")
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<string>("ShortDesc")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("PackageId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("package_translation", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageUpdateConfig", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoCreated")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastCommit")
                        .HasColumnType("text");

                    b.Property<string>("LastTag")
                        .HasColumnType("text");

                    b.Property<bool>("MakeRelease")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("OutdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ref")
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .HasColumnType("text");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("PackageId");

                    b.ToTable("package_update_config", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PairedDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentServerAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset?>("PresenceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "PresenceUpdatedAt");

                    b.ToTable("paired_device", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaderId")
                        .HasColumnType("integer");

                    b.Property<string>("ServerAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LeaderId");

                    b.ToTable("party", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PartyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PartyId", "UserId")
                        .IsUnique();

                    b.ToTable("party_member", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FixedPasswordEncrypted")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PasswordListEncrypted")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("PasswordType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RotateIndex")
                        .HasColumnType("integer");

                    b.Property<string>("SkinUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("player_character", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.ServerCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InvalidReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("UserId", "Address")
                        .IsUnique();

                    b.ToTable("server_credential", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Thread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ReviewId");

                    b.ToTable("thread", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.ThreadReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStatusUpdate")
                        .HasColumnType("boolean");

                    b.Property<int>("ThreadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ThreadId");

                    b.ToTable("thread_reply", (string)null);
                });

            modelBuilder.Entity("ContentDB.Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultServerUsername")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DonateUrl")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EmailConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ForumsUsername")
                        .HasColumnType("text");

                    b.Property<string>("GithubUsername")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("OidcIssuer")
                        .HasColumnType("text");

                    b.Property<string>("OidcSubject")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicUrl")
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("OidcIssuer", "OidcSubject");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("content_warnings", b =>
                {
                    b.Property<int>("ContentWarningsId")
                        .HasColumnType("integer");

                    b.Property<int>("PackagesId")
                        .HasColumnType("integer");

                    b.HasKey("ContentWarningsId", "PackagesId");

                    b.HasIndex("PackagesId");

                    b.ToTable("content_warnings");
                });

            modelBuilder.Entity("maintainers", b =>
                {
                    b.Property<int>("MaintainedPackagesId")
                        .HasColumnType("integer");

                    b.Property<int>("MaintainersId")
                        .HasColumnType("integer");

                    b.HasKey("MaintainedPackagesId", "MaintainersId");

                    b.HasIndex("MaintainersId");

                    b.ToTable("maintainers");
                });

            modelBuilder.Entity("provides", b =>
                {
                    b.Property<int>("PackagesId")
                        .HasColumnType("integer");

                    b.Property<int>("ProvidesId")
                        .HasColumnType("integer");

                    b.HasKey("PackagesId", "ProvidesId");

                    b.HasIndex("ProvidesId");

                    b.ToTable("provides");
                });

            modelBuilder.Entity("tags", b =>
                {
                    b.Property<int>("PackagesId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("PackagesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("thread_watchers", b =>
                {
                    b.Property<int>("ThreadId")
                        .HasColumnType("integer");

                    b.Property<int>("WatchersId")
                        .HasColumnType("integer");

                    b.HasKey("ThreadId", "WatchersId");

                    b.HasIndex("WatchersId");

                    b.ToTable("thread_watchers");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.APIToken", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.OAuthClient", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("ContentDB.Core.Domain.User", "Owner")
                        .WithMany("Tokens")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.Navigation("Client");

                    b.Navigation("Owner");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.AuditLogEntry", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Causer")
                        .WithMany()
                        .HasForeignKey("CauserId");

                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.Navigation("Causer");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Collection", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Author")
                        .WithMany("Collections")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.CollectionPackage", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Collection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Dependency", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Package", "Depender")
                        .WithMany("Dependencies")
                        .HasForeignKey("DependerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.MetaPackage", "MetaPackage")
                        .WithMany("Dependencies")
                        .HasForeignKey("MetaPackageId");

                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.Navigation("Depender");

                    b.Navigation("MetaPackage");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.DevicePairing", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.PairedDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("ContentDB.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.ForumTopic", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.FriendLink", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Addressee")
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.GameServer", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Notification", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Causer")
                        .WithMany()
                        .HasForeignKey("CauserId");

                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.HasOne("ContentDB.Core.Domain.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Causer");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.OAuthClient", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Owner")
                        .WithMany("OAuthClients")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Package", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Author")
                        .WithMany("Packages")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.PackageScreenshot", "CoverImage")
                        .WithMany()
                        .HasForeignKey("CoverImageId");

                    b.HasOne("ContentDB.Core.Domain.License", "License")
                        .WithMany("Packages")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.License", "MediaLicense")
                        .WithMany()
                        .HasForeignKey("MediaLicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.Thread", "ReviewThread")
                        .WithMany()
                        .HasForeignKey("ReviewThreadId");

                    b.Navigation("Author");

                    b.Navigation("CoverImage");

                    b.Navigation("License");

                    b.Navigation("MediaLicense");

                    b.Navigation("ReviewThread");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageAlias", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany("Aliases")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageDailyStats", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageGameSupport", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Package", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany("SupportedGames")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageRelease", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.LuantiRelease", "MaxRel")
                        .WithMany()
                        .HasForeignKey("MaxRelId");

                    b.HasOne("ContentDB.Core.Domain.LuantiRelease", "MinRel")
                        .WithMany()
                        .HasForeignKey("MinRelId");

                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany("Releases")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaxRel");

                    b.Navigation("MinRel");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageReview", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany("Reviews")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.Thread", "Thread")
                        .WithMany()
                        .HasForeignKey("ThreadId");

                    b.Navigation("Author");

                    b.Navigation("Package");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageReviewVote", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.PackageReview", "Review")
                        .WithMany("ReviewVotes")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageScreenshot", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany("Screenshots")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageTranslation", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany("Translations")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageUpdateConfig", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithOne("UpdateConfig")
                        .HasForeignKey("ContentDB.Core.Domain.PackageUpdateConfig", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PairedDevice", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "User")
                        .WithMany("PairedDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Party", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PartyMember", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Party", "Party")
                        .WithMany("Members")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PlayerCharacter", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.ServerCredential", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.PlayerCharacter", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContentDB.Core.Domain.User", "User")
                        .WithMany("ServerCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Thread", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.Package", "Package")
                        .WithMany("Threads")
                        .HasForeignKey("PackageId");

                    b.HasOne("ContentDB.Core.Domain.PackageReview", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId");

                    b.Navigation("Author");

                    b.Navigation("Package");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.ThreadReply", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.Thread", "Thread")
                        .WithMany("Replies")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("content_warnings", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.ContentWarning", null)
                        .WithMany()
                        .HasForeignKey("ContentWarningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("maintainers", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("MaintainedPackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("MaintainersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("provides", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.MetaPackage", null)
                        .WithMany()
                        .HasForeignKey("ProvidesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tags", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("thread_watchers", b =>
                {
                    b.HasOne("ContentDB.Core.Domain.Thread", null)
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentDB.Core.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("WatchersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Collection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.License", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.MetaPackage", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Package", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Dependencies");

                    b.Navigation("Releases");

                    b.Navigation("Reviews");

                    b.Navigation("Screenshots");

                    b.Navigation("SupportedGames");

                    b.Navigation("Threads");

                    b.Navigation("Translations");

                    b.Navigation("UpdateConfig");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.PackageReview", b =>
                {
                    b.Navigation("ReviewVotes");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Party", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.Thread", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("ContentDB.Core.Domain.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Collections");

                    b.Navigation("Notifications");

                    b.Navigation("OAuthClients");

                    b.Navigation("Packages");

                    b.Navigation("PairedDevices");

                    b.Navigation("ServerCredentials");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
